
CREATE MATERIALIZED VIEW ROADEVENTS_STAR AS
SELECT * FROM ROADEVENTS_FACT   F
JOIN TIME_DIM  T ON T.DAY_ID = F.TIME_DIM_ID
JOIN ROAD_DIM  R ON R.SEGMENT_ID = F.ROAD_DIM_ID
JOIN EVENT_DIM E ON E.EVENT_ID = F.EVENT_DIM_ID
